// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAmaCbsElMOg-D6jQT83j1UYpwJbT-7Q',
    appId: '1:910496426601:web:06191db75c2db23cd290f8',
    messagingSenderId: '910496426601',
    projectId: 'malva-7084e',
    authDomain: 'malva-7084e.firebaseapp.com',
    storageBucket: 'malva-7084e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WngBVWc7qNsZ41TRj-MsCEnb-WGDVpA',
    appId: '1:910496426601:android:aa5c7b5ac0dbcdbdd290f8',
    messagingSenderId: '910496426601',
    projectId: 'malva-7084e',
    storageBucket: 'malva-7084e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAmaCbsElMOg-D6jQT83j1UYpwJbT-7Q',
    appId: '1:910496426601:web:de9e8c11e3cb5abbd290f8',
    messagingSenderId: '910496426601',
    projectId: 'malva-7084e',
    authDomain: 'malva-7084e.firebaseapp.com',
    storageBucket: 'malva-7084e.firebasestorage.app',
  );
}
